version: '2'

services:
  pong-io:
    container_name: pong-io
    build: ./
    ports:
      - 1234:1234 # Http Port
      - 1233:1233 # Socket Port
    volumes:
      - ./:/var/www

networks:
  default:
    external:
      name: pong-io
